name: Build

on:
  push:
    branches: [ source ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init Node env
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: yarn install
    - run: yarn run build
    - name: push to dist branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        publish_branch: master
        cname: ljl.li
